### ISSUE TITLE
FileUploadActivity에서 파일 업로드시 반응 없음

### ISSUE THREAD

**Issue by potados99** [inu-appcenter/Share_U_Android#15]
## 배경

- Target SDK: 29
- Minimum SDK: 23
- Retrofit2: v2.3.0
- Server base url: http://117.16.231.66:7001

## 조건

- 애플리케이션 실행 후 로그인 상태 진입 (로컬 저장소에 토큰 확보).
- 파일 업로드 화면으로 이동
- 파일 제목: 아무 스트링 (선택된 파일은 적절히 작은 JPEG 이미지)
- 과목 선택: 아무 스트링
- 담당 교수: 아무 스트링
- 내용: 길이 30 이상 아무 스트링

## 증상

업로드 버튼 클릭 후, 서버에 요청을 전달하는 [메소드 실행](https://github.com/inu-appcenter/Share_U_Android/blob/195484e7c039ba06ca9ac44af944bf16e29b1737/app/src/main/java/com/inuappcenter/shareu/activity/FileUploadActivity.java#L160) 후 장시간 응답이 없다가 `onFailure` 콜백이 실행됨. 

해당 콜백에 인자로 넘겨진 `Throwable` 객체에 대해 `printStackTrace()` 메소드를 실행한 결과는 다음과 같음:

~~~
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:41)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
        at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
        at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:124)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
    	... 27 more
~~~

## 실제 요청 파라미터의 내용:
~~~
- title: C!
- content: hhihxjdjjdwdjedjwdjwskidrjcekdowdedkepdeldelxkwdlw 
- subjectName: C언어프로그래밍(1) 
- profName: 전경구 
- token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTYwMTY1NyIsIm5hbWUiOiLsnKDsp4DsiJgiLCJtYWpvciI6Iuy7tO2TqO2EsOqzte2Vmeu2gCIsInRlbCI6IjAxMDYzNzc0NjQxIiwidHlwZSI6MSwiaWF0IjoxNTgzMTY1NDc0LCJleHAiOjE1ODU3NTc0NzQsInN1YiI6InVzZXJJbmZvIn0.EJ9jC-wFl1Uf5MITxccS2efzgIMH13inzwGCJ13n9BA
- filePart: okhttp3.MultipartBody$Part@218fdb4
~~~

**Comment by potados99** [comment]
## 클라이언트의 잘못인가, 서버의 잘못인가

업로드 API는 다음과 같음:

~~~
Method: POST
Path: /document/upload/uploadfile
Body(multipart/form-data):
- title: 자료의 제목
- content: 자료의 본문
- subjectName: 자료가 다루는 과목의 이름
- profName: 해당 과목의 담당교수 이름
- token: 로그인 토큰
- (수정) userfile: 올릴 파일
~~~

Postman을 사용해보면 답이 나올 것.

## Postman 테스트

### 테스트 케이스 1

- Method: POST
- URL:  http://117.16.231.66:7001/document/upload/uploadfile

- Body(form-data):
> title: C! 
> content: hhihxjdjjdwdjedjwdjwskidrjcekdowdedkepdeldelxkwdlw 
> subjectName: C언어프로그래밍(1) 
> profName: 전경구 
> token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTYwMTY1NyIsIm5hbWUiOiLsnKDsp4DsiJgiLCJtYWpvciI6Iuy7tO2TqO2EsOqzte2Vmeu2gCIsInRlbCI6IjAxMDYzNzc0NjQxIiwidHlwZSI6MSwiaWF0IjoxNTgzMTY1NDc0LCJleHAiOjE1ODU3NTc0NzQsInN1YiI6InVzZXJJbmZvIn0.EJ9jC-wFl1Uf5MITxccS2efzgIMH13inzwGCJ13n9BA
> filePart: 데스크탑에 저장된 작은 JPEG 이미지 사용

**결과**: 500 Internal Server Error

### 테스트 케이스 2

- Method: POST
- URL:  http://117.16.231.66:7001/document/upload/uploadfile

- Body(form-data):
> title: C! 
> content: hhihxjdjjdwdjedjwdjwskidrjcekdowdedkepdeldelxkwdlw 
> subjectName: C언어프로그래밍(1) 
> profName: 전경구 
> token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwMTYwMTY1NyIsIm5hbWUiOiLsnKDsp4DsiJgiLCJtYWpvciI6Iuy7tO2TqO2EsOqzte2Vmeu2gCIsInRlbCI6IjAxMDYzNzc0NjQxIiwidHlwZSI6MSwiaWF0IjoxNTgzMTY1NDc0LCJleHAiOjE1ODU3NTc0NzQsInN1YiI6InVzZXJJbmZvIn0.EJ9jC-wFl1Uf5MITxccS2efzgIMH13inzwGCJ13n9BA

(위와 같으나 filePart 부분만 제외)

**결과**: No response (timeout)

### 결론: 둘다

서버는 파라미터가 단 하나라도 빠지면 **응답을 보내지 않아** 클라이언트가 timeout 상태에 빠져들게 된다.

Android 클라이언트에서 timeout 에러가 발생하였다.

Android 클라이언트는 유효한 파라미터 하나 이상 부재한, 즉 API 규격에 맞지 않는 요청을 보내고 있다.

**Comment by potados99** [comment]
## 요청 코드 뜯어보기

Android 클라이언트에서 보내는 요청의 파라미터를 명시한 메소드는 아래와 같이 정의된다:
~~~
    @Multipart
    @POST("/document/upload/uploadfile")
    Call<ResponseBody> uploadImage(@Part("title") String  title, @Part("content") String content,
                                   @Part("subjectName") String subjectName,
                                   @Part("profName") String profName,
                                   @Part("token")String token,@Part MultipartBody.Part filePart);
~~~
([이 곳](https://github.com/inu-appcenter/Share_U_Android/blob/195484e7c039ba06ca9ac44af944bf16e29b1737/app/src/main/java/com/inuappcenter/shareu/service/RetrofitService.java#L61) 참조)

String과 MultipartBody.Part가 함께 사용되고 있다.

이 메소드의 구현을 호출할 때에 넘겨줄 filePart를 만드는 부분의 코드는 다음과 같다:

~~~
        File imageFile = new File(path);
        RequestBody reqFile = RequestBody.create(type, imageFile);
        filePart = MultipartBody.Part.createFormData("userFile", imageFile.getName(), reqFile);
~~~

즉, 파일을 하나의 폼 데이터로 보고 다루고 있다. 그렇다면 `MultipartBody.Part.createFormData ` 메소는 파일만을 다루는 용도일까? 이름을 보아 하니 그렇지 않다.

우리가 파일 body를 담은 폼 데이터를 만들 때 사용한 메소드의 원형은 다음과 같다:

~~~
// MultipartBody.java line 247
public static Part createFormData(String name, @Nullable String filename, RequestBody body)
~~~

그 바로 위에 다른 오버로드가 존재한다.

~~~
// MultipartBody.java line 243
public static Part createFormData(String name, String value)
~~~

`RequestBody.create` 또한 여러 오버로드가 존재한다.

~~~
// RequestBody.java line 104
public static RequestBody create(final @Nullable MediaType contentType, final File file)

// same file, line 47
public static RequestBody create(@Nullable MediaType contentType, String content)
~~~

그렇다. Retrofit service의 메소드를 정의할 때에 파라미터를 `@Part("title") String title`와 같이 만들어 자동으로 request body가 생성되도록 할 수 있지만, 직접 `RequestBody.create`사용하여 이를 파라미터가 `@Part("title") RequestBody title`의 모양으로 주어지는 메소드에 방금 만든 Request body를 넘겨줄 수도 있는 것이다.

이 두 방법을 혼용하는 것이 바람직한 것인지 알 수 없다.

[Retrofit 2 can't upload a file with two additional separate string parameters](https://stackoverflow.com/questions/36088444/retrofit-2-cant-upload-a-file-with-two-additional-separate-string-parameters)라는 이름으로 비슷한 질문이 올라왔다.

이것을 문제의 원인으로 보고 위 글의 답변이 제시한 대로 요청 메소드 원형과 호출 부분을 바꾸어 보았다.

전:
~~~
    @Multipart
    @POST("/document/upload/uploadfile")
    Call<ResponseBody> uploadImage(@Part("title") String  title, @Part("content") String content,
                                   @Part("subjectName") String subjectName,
                                   @Part("profName") String profName,
                                   @Part("token")String token,@Part MultipartBody.Part filePart);
~~~

후:

~~~
    @Multipart
    @POST("/document/upload/uploadfile")
    Call<ResponseBody> uploadImage(@Part("title") RequestBody title, @Part("content") RequestBody content,
                                   @Part("subjectName") RequestBody subjectName,
                                   @Part("profName") RequestBody profName,
                                   @Part("token") RequestBody token,@Part MultipartBody.Part filePart);
~~~

호출 부분도 다음과 같이 변경하였다:

~~~

                            RequestBody titleBody = RequestBody.create(
                                    MediaType.parse("text/plain"),
                                    edtv_file_name.getText()+""
                            );


                            RequestBody contentBody = RequestBody.create(
                                    MediaType.parse("text/plain"),
                                    edtv_content.getText()+""
                            );

                            RequestBody subjectNameBody = RequestBody.create(
                                    MediaType.parse("text/plain"),
                                    edtv_select_subject.getText()+""
                            );

                            RequestBody profNameBody = RequestBody.create(
                                    MediaType.parse("text/plain"),
                                    edtv_select_prof.getText()+""
                            );

                            RequestBody tokenBody = RequestBody.create(
                                    MediaType.parse("text/plain"),
                                    token
                            );


                            service.uploadImage(
                                    titleBody,
                                    contentBody,
                                    subjectNameBody,
                                    profNameBody,
                                    tokenBody,
                                    filePart
                            ).enqueue(...);
~~~

테스트 결과 **변화 없다**.

**Comment by potados99** [comment]
## HTTP 요청을 뜯어보자.

위 메소드 변경으로 인해 실제로 변한 것이 있을까?

Android 클라이언트의 요청 Postman의 요청과 어떻게 다를까?
 
다음 세 요청을 비교해보겠다:

- Android 변경 전
- Android 변경 후
- Postman

### Android 변경 전

Android의 네트워크 흐름을 캡쳐하기 위해 tPacketCapture라는 애플리케이션을 사용하였다.

pcap 파일 분석은 Wireshark를 사용하였다.

POST 요청은 다음과 같이 캡쳐되었다:

~~~
12545	2.494316	10.8.0.1	117.16.231.66	HTTP	341	POST /document/upload/uploadfile HTTP/1.1  (text/plain) (text/plain) (text/plain) (text/plain) (text/plain)
~~~

해당 메시지를 분석해보는데, `Encapsulated multipart part:  (multipart/form-data)` 부분에 빨간 줄이 떴다.

살펴보니, 다른 메시지들은 `Encapsulated multipart part:  (text/plain)`인데 파일 부분만 유독 저 타입이었다.

"multipart/form-data" 스트링이 위치한 곳은 [이 곳](https://github.com/inu-appcenter/Share_U_Android/blob/195484e7c039ba06ca9ac44af944bf16e29b1737/app/src/main/java/com/inuappcenter/shareu/activity/FileUploadActivity.java#L318)이다.

**multipart/form-data는 파일에 해당하는 MIME type이 아니다.**

`image/png`, `image/jpeg` 등이 들어가야 맞다.

image/jpeg로 변경 후 다시 시도했으나 **같은 동작**.

~~~
12558	2.283561	10.8.0.1	117.16.231.66	HTTP	331	POST /document/upload/uploadfile HTTP/1.1  (text/plain) (text/plain) (text/plain) (text/plain) (text/plain) (JPEG JFIF image)
~~~

다음으로 Postman의 요청을 분석한다.

### Postman

~~~
12558	2.283561	10.8.0.1	117.16.231.66	HTTP	331	POST /document/upload/uploadfile HTTP/1.1  (text/plain) (text/plain) (text/plain) (text/plain) (text/plain) (JPEG JFIF image)
~~~

이렇게 온다.

Android에서 보낸 것과 별반 다름이 없다.

다음 요소들이 완전히 일치한다:

- 각 body 파라미터의 순서
- 각 body 파라미터의 타입
- 각 body 파라미터의 값

헤더의 몇 필드를 제외하면 서버가 받아들이는 값은 완전히 동일한 유형일 것으로 예상되나 여전히 두 요청은 서버에게 다르게 받아들여진다.

## 서버 코드를 뜯어보자

이건 서버 소스코드를 보는 것이 빠르다.

서버 소스코드는 다음 문제가 있다:

- 요청이 이상할 경우 400 Bad request 응답을 보내야 하는데 아무 응답이 없다. 즉, 라우터 로직에 res 호출 없이 콜백이 종료되는 branch가 존재한다.

- 아무리 봐도 요청 잘 보냈는데(postman으로도) 500 Internal error로 답한다.

**Comment by potados99** [comment]
# Oh, FUCK! MY MISSTAKE !!!

[여기](https://github.com/inu-appcenter/shareU_Server/blob/2d5acb7a5700efa0b4a321bc3ae7d1614e20eae2/routes/document/upload.js#L42) 주목!!!!

**파일 부분 이름은 알고보니 userfile이었다...**

[안드로이드쪽 소스](https://github.com/inu-appcenter/Share_U_Android/blob/195484e7c039ba06ca9ac44af944bf16e29b1737/app/src/main/java/com/inuappcenter/shareu/activity/FileUploadActivity.java#L322)에 잘 쓰여 있었는데, 테스트하느라고 바꾸다가 놓쳤다. 죄송... :)

**Comment by potados99** [comment]
## Postman 다시 테스트

`filePart`를 `userFile`로 바꿨다
드디어 200 응답이 온다.

~~~
{
    "ans": true
}
~~~

**Comment by ryuspace** [comment]
꺄라라랄아알아랑랑랑라알ㅇㄹㅇ라알 병준몬 제일최고 ㄱ꺄랼알아라아랑라아랑랑 적게 일하고 많이 벌어 >< >< ><

**Comment by potados99** [comment]
## Android 테스트 성공

[요 커밋](https://github.com/inu-appcenter/Share_U_Android/commit/50aa3cd8aeb9e00acd7b20bf7e1dd981a8041f5d) 참고.

결국 위 질문([Retrofit 2 can't upload a file with two additional separate string parameters](https://stackoverflow.com/questions/36088444/retrofit-2-cant-upload-a-file-with-two-additional-separate-string-parameters))과 비슷한 유형의 문제였는 듯.

**Comment by potados99** [comment]
> 꺄라라랄아알아랑랑랑라알ㅇㄹㅇ라알 병준몬 제일최고 ㄱ꺄랼알아라아랑라아랑랑 적게 일하고 많이 벌어 >< >< ><

감사합니다 ><
