### ISSUE TITLE
Retrofit response code가 403

### ISSUE THREAD

**Issue by ryuspace** [inu-appcenter/Share_U_Android#17]
@@예상 응답
{
    "ans": true,
    "rows": [
        {
            "title": "re/app/debug/app-de",
            "subjectName": "Academic English",
            "profName": "김연정",
            "content": "https://github.com/inu-appcenter/Share_U_Android/blob/feature/app/debug/app-debug.apk",
            "uploadDate": "2020-03-04",
            "uploadId": "201601657",
            "extension": "apk",
            "division": "교양"
        }
    ]
}

//ServiceInterface
    @FormUrlEncoded
    @POST("/document/send/documentPage")
    Call<documentPage>documentPage(@Field("documentKey")int key,@Field("uploadId")String token);

public class documentPage
{
    @SerializedName("ans")
    public boolean ans;

    @SerializedName("rows")
    public List<Row> rows;

    public class Row{

        @SerializedName("title")
        public String title;
        @SerializedName("subjectName")
        public String subjectName;
        @SerializedName("profName")
        public String profName;
        @SerializedName("content")
        public String content;
        @SerializedName("uploadDate")
        public String uploadDate;
        @SerializedName("uploadId")
        public String uploadId;
        @SerializedName("extension")
        public String extension;
        @SerializedName("division")
        public String division;
    }

}

//통신부분
        TokenManager tm = TokenManager.getInstance();

        String token = tm.getToken(this);
        RetrofitService networkService = RetrofitHelper.create();
        networkService.documentPage(key,token).enqueue(new Callback<documentPage>() {
            @Override
            public void onResponse(Call<documentPage> call, Response<documentPage> response) {

                if (response.isSuccessful()) {
                    tv_my_major.setText(response.body().rows.get(0).title);
                    tv_detailed_file_content.setText(response.body().rows.get(0).content);
                    //review_ratingbar.setRating(response.body().get(0).get);
                    String name = response.body().rows.get(0).uploadId;
                    name=name.substring(0,5);
                    name+="****";
                    tv_detailed_file_user_name.setText(name);
                    //tv_detailed_file_category.setText(response.body().get(0))
                    tv_detailed_file_date.setText(response.body().rows.get(0).uploadDate);
                    tv_detailed_file_category.setText(response.body().rows.get(0).division);
                    tv_detailed_file_type.setText(response.body().rows.get(0).extension);
                    tv_detailed_file_name.setText(response.body().rows.get(0).title);
                }

            }

            @Override
            public void onFailure(Call<documentPage> call, Throwable t) {

            }
        });
이렇게 받았는데 403 에러가 뜬다.

레트로핏 통신하는 부분은 DetailedFileActivity에 giveMeList 함수 안에 있다.

**Comment by potados99** [comment]
파라미터 이름을 `token`으로 보내면 된다
