### ISSUE TITLE
액티비티가 사라졌는데 프래그먼트를 실행하려고 한다...?!

### ISSUE THREAD

**Issue by ryuspace** [inu-appcenter/Share_U_Android#21]
![image](https://user-images.githubusercontent.com/40001772/76220254-84094480-625a-11ea-8b4a-d818742cd177.png)

Share U 앱의 자료 상세화면이다. 이 때 사용자가 자료 받기를 누르면 상단바에 다운로드 진행상황이 그려지고 다 받으면 

![image](https://user-images.githubusercontent.com/40001772/76220340-a733f400-625a-11ea-9fab-3a015be0fe26.png)
이런식으로 밑에 BottomSheet가 뜬다.

하지만...!

자료를 받는 시간이 길어지면 사용자는 이 액티비티를 이탈할 가능성이 매우 매우 높다.
다행히 백그라운드에서 자료를 다운받을 수 있는 라이브러리를 선정해 다운은 계속 되지만
액티비티가 사라져서 다운이 완료되면 에러가 떠버린다.

이미 죽은 activity에서 fragment가 붙으려고 하기 때문이다.

단순히 액티비티가 죽으면 fragment를 무시하면 사용자는 진행상황을 모른다..!

그래서, activity가 pause를 거치면 (액티비티가 가려지거나 죽은 경우)
flag를 설정해 액티비티가 보여지는 상탠지 체크를 하고,

보여지면 BottomSheet를 띄우지만 보여지지 않으면

![image](https://user-images.githubusercontent.com/40001772/76220558-0abe2180-625b-11ea-9051-5c2324a634e9.png)

intent를 이용해 새 액티비티를 띄우게 했다!

근데.. 액티비티가 죽었는데 그 액티비티에서 새로운 액티비티 뜨는건 왜 되지...? ㅎㅎㅎㅎ

예상 : 어플리케이션의 Context를 받아서 그런거겠지? getApplicationContext 말고 Activity.this 하면 아마 죽을 거다. 이미 액티비티가 사라졌으니

getApplicationContext 안 죽음
DetailedFileActivity.this 안 죽음
getBaseContext 안 죽음

**Comment by ryuspace** [comment]
Activity의 Context는 Activity가 Destroy가 되어도 메모리에서 제거되지 않는다고 한다!
참고 : 

> ApplicationContext는 싱글톤으로 프로세스에서 1개만 존재합니다. 싱글톤과 같은 오프젝트를 초기화 할 때 혹은 전역적으로 사용할 레퍼런스를 초기화 할 때 사용하면 좋다. 반면에 Context는 라이프 사이클을 잘 생각해야 합니다. 만약 싱글톤에 Acitvity의 Context를 사용하면 Activity가 Destory 되어도 메모리에서 제거되지 않습니다. 이는 GC의 대상이 되기 위에서는 모든 객체의 참조가 null이 되어야 하기 때문입니다. Acitivty는 파괴되었지만 싱글톤에 참조되어 있기 때문에 제거되지 않고 이는 메모리릭으로 직결됩니다. 따라서 컴포넌트의 라이프 사이클 안에서만 사용할 경우 Context를 쓰고 전역적으로 사용할 경우에는 ApplicationContext를 사용하자!!.



실제로
`Activity activity = MainActivity.this;
if (activity.isFinishing())
return;
`

이런 코드가 가능하다..! 액티비티가 죽었는지 판단하는 코드이다.

**Comment by ryuspace** [comment]
![image](https://user-images.githubusercontent.com/40001772/76228226-c97e3f80-6263-11ea-9883-987c34d7e318.png)
아하 Activity.this는 살아있으면 살아있다는 Context를 나타내주고 죽었으면 죽어있다는 Context를 알려주는거구나!

**Comment by ryuspace** [comment]
![image](https://user-images.githubusercontent.com/40001772/76228479-21b54180-6264-11ea-9852-a41e19d74c4c.png)
Application Context는 앱 종료 후에도 Context를 사용할 수 있다 (아직 와닿지는 않음)
BaseContext는 앱 종료후 메모리에서 제거된다!

**Comment by ryuspace** [comment]
그래서 해결방법..
Application Context를 받는 SingleTon 객체를 만들어 필요할 때 마다 사용하였다.

우선 전체 코드를 보자면 

`public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Navigator.setContext(getApplicationContext());
    }
}
`
Application을 상속 받는 클래스를 만든다. 여기서의 onCreate는 안드로이드 앱 시작 후 최초로 불리는 루틴이다.

`public class Navigator{
    private static Context context;

    public static void setContext(Context context)
    {
        if(context == null)
        {
            throw new RuntimeException("WTF");
        }
        Navigator.context=context;
    }
    public static void launchActicity(Class<?> clazz)
    {
        if(Navigator.context == null)
        {
            throw new RuntimeException("WTF ? setContext first!");
        }
        Intent intent = new Intent(Navigator.context,clazz);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        Navigator.context.startActivity(intent);
    }
}`

그리고 Navigator라는 SingleTon 객체를 만든다.
ApplicationContext는 주로 화면 전환을 할 때 많이 쓰므로 launchActivity 메소드를 받아서
매개변수로 들어온 클래스를 실행하는 역할로 사용하였다.

**Comment by bungabear** [comment]
Context에 몇가지 종류가 있습니다.
아래 표는 제가 두고두고 잘 써먹었기에 공유드려요~

표에도 써있고 경험해보셨겠지만, ActivityContext가 아닌 경우 Intent.FLAG_ACTIVITY_NEW_TASK가 꼭 필요해요!!
![image](https://user-images.githubusercontent.com/22841704/83409102-afad5c80-a44e-11ea-938e-90eccb0aad40.png)
